import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { AgentV, localExecutionScope, resolveToolExecutionPolicy } from "../dist/core/index.js";
import { AiSdkToolAgentEngine } from "../dist/adapters/ai-sdk/index.js";
import { LocalCliRuntimeDiscovery, LocalCliRuntimeEngine } from "../dist/adapters/local-cli/index.js";
import { OllamaRuntime } from "../dist/adapters/ollama/index.js";
import { ProviderRuntime, defineProviderProfile } from "../dist/adapters/providers/index.js";
import { createAgentRuntime } from "../dist/runtime/index.js";
import { builtInAgentRecipes, builtInAgentSkills } from "../dist/skills/index.js";
import { createCalculatorTool, createStandardApprovalPolicy, standardToolNames } from "../dist/tools/index.js";
import { createFilesystemTools } from "../dist/tools/node/index.js";
import { discoverAgentSkillInventory, JsonSessionStore, loadSkillPackage, SystemCredentialStore } from "../dist/node/index.js";
import { FakeToolAgentEngine } from "../dist/testing/index.js";

assert.equal(typeof AgentV, "function");
assert.equal(typeof localExecutionScope, "function");
assert.equal(resolveToolExecutionPolicy({ afterRequired: "disable" }).afterRequired, "disable");
assert.equal(typeof AiSdkToolAgentEngine, "function");
assert.equal(typeof LocalCliRuntimeEngine, "function");
assert.equal(typeof LocalCliRuntimeDiscovery, "function");
assert.equal(typeof OllamaRuntime, "function");
assert.equal(typeof ProviderRuntime, "function");
assert.equal(typeof defineProviderProfile, "function");
assert.equal(typeof createAgentRuntime, "function");
assert.equal(builtInAgentRecipes.coding.id, "coding");
assert.equal(builtInAgentRecipes.planning.id, "planning");
assert.equal(builtInAgentRecipes.debugging.id, "debugging");
assert.equal(builtInAgentRecipes.security.id, "security");
assert.equal(builtInAgentRecipes.frontend.id, "frontend");
assert.equal(builtInAgentSkills.repositoryComprehension.id, "repository-comprehension");
assert.equal(standardToolNames.applyWorkspacePatch, "apply-workspace-patch");
assert.equal(standardToolNames.browserConsole, "browser-console");
assert.equal(createCalculatorTool().name, "calculate");
assert.equal(typeof createStandardApprovalPolicy, "function");
assert.equal(typeof createFilesystemTools, "function");
assert.equal(typeof JsonSessionStore, "function");
assert.equal(typeof loadSkillPackage, "function");
assert.equal(typeof discoverAgentSkillInventory, "function");
assert.equal(typeof SystemCredentialStore, "function");
assert.equal(typeof FakeToolAgentEngine, "function");

const publicProviders = await import("@vraxis/agent-v/providers");
const publicNode = await import("@vraxis/agent-v/node");
const publicRuntime = await import("@vraxis/agent-v/runtime");
const publicSkills = await import("@vraxis/agent-v/skills");
const publicTools = await import("@vraxis/agent-v/tools");
const publicNodeTools = await import("@vraxis/agent-v/tools/node");
assert.equal(publicProviders.ProviderRuntime, ProviderRuntime);
assert.equal(publicNode.SystemCredentialStore, SystemCredentialStore);
assert.equal(publicRuntime.createAgentRuntime, createAgentRuntime);
assert.equal(publicSkills.builtInAgentRecipes.coding.id, "coding");
assert.equal(publicTools.createCalculatorTool().name, "calculate");
assert.equal(publicNodeTools.createFilesystemTools, createFilesystemTools);

const cli = spawnSync(process.execPath, ["dist/cli/index.js", "--help"], { encoding: "utf8" });
assert.equal(cli.status, 0, cli.stderr);
assert.match(cli.stdout, /doctor\s+Inspect dependencies/);

const skillPath = spawnSync(process.execPath, ["dist/cli/index.js", "skill-path"], { encoding: "utf8" });
assert.equal(skillPath.status, 0, skillPath.stderr);
assert.match(skillPath.stdout, /skills[/\\]agent-v/);
