export const standardToolNames = {
  calculate: "calculate",
  dateTime: "date-time",
  validateJson: "validate-json",
  listDirectory: "list-directory",
  findFiles: "find-files",
  readText: "read-text",
  searchText: "search-text",
  writeText: "write-text",
  applyTextEdits: "apply-text-edits",
  applyWorkspacePatch: "apply-workspace-patch",
  createDirectory: "create-directory",
  movePath: "move-path",
  removePath: "remove-path",
  gitStatus: "git-status",
  gitDiff: "git-diff",
  gitLog: "git-log",
  gitShow: "git-show",
  runCommand: "run-command",
  httpFetch: "http-fetch",
  browserSnapshot: "browser-snapshot",
  browserConsole: "browser-console",
  browserScreenshot: "browser-screenshot",
  browserWait: "browser-wait",
  browserNavigate: "browser-navigate",
  browserClick: "browser-click",
  browserType: "browser-type",
} as const;
